"use client";
import { useEffect, useState } from "react";
import { getLocalProfileId } from "@/lib/progress/client";

type Progress = { profile: { alias: string; publicRanking: boolean; calibration: Record<string,number> } | null; attempts: { id:string; scenarioTitle:string; difficulty:string; mode:string; outcome?:{label:string;score:number}; skillScores?:Record<string,number>; comparison?:{scoreDelta:number}; createdAt:string }[]; skills:{name:string;mode:string;score:number;attempts:number;trend:number}[]; recommendation:{skill:string;explanation:string;scenarioId:string}; achievements:{id:string;title:string;description:string;earned:boolean}[]; calibrationCount:number; calibrationReady:boolean; totalAttempts:number; totalPoints:number };
const anchors = [
  { id:"interests", title:"Выяснение интереса", text:"«Что для вас важнее всего в этом запуске и почему именно это?»", low:"Не уточнять интересы", middle:"Задать общий вопрос о задаче", high:"Выяснить приоритет и причину" },
  { id:"limits", title:"Работа с ограничениями", text:"«Не назову срок до проверки зависимости; могу вернуться с подтверждённой датой завтра».", low:"Пообещать срок без проверки", middle:"Сказать, что есть риск", high:"Обозначить границу и следующий шаг" },
  { id:"agreement", title:"Следующий шаг", text:"«Зафиксируем объём пилота, ответственного и дату проверки результата?»", low:"Закончить без договорённости", middle:"Предложить продолжить позже", high:"Согласовать действие и проверку" },
];
export default function ProgressPage() {
  const [id,setId]=useState(""); const [data,setData]=useState<Progress|null>(null); const [alias,setAlias]=useState(""); const [publicRanking,setPublicRanking]=useState(false); const [calibration,setCalibration]=useState<Record<string,number>>({}); const [status,setStatus]=useState(""); const [scenarios,setScenarios]=useState<{id:string;title:string;difficulty?:string;version?:number}[]>([]); const [scenarioId,setScenarioId]=useState(""); const [scenarioVersion,setScenarioVersion]=useState(1); const [difficulty,setDifficulty]=useState("Средняя"); const [rows,setRows]=useState<{alias:string;score:number;attempts:number;outcome:string}[]>([]);
  async function refresh(profileId:string) { const res=await fetch(`/api/progress?profileId=${encodeURIComponent(profileId)}`); const result=await res.json(); setData(result); setAlias(result.profile?.alias ?? "Переговорщик"); setPublicRanking(result.profile?.publicRanking ?? false); setCalibration(result.profile?.calibration ?? {}); }
  useEffect(()=>{const profileId=getLocalProfileId(); setId(profileId); void refresh(profileId); void fetch("/api/scenarios").then(r=>r.json()).then(list=>{setScenarios(list); if(list[0]) {setScenarioId(list[0].id);setScenarioVersion(list[0].version??1);}});},[]);
  async function save(patch:Record<string,unknown>) { const res=await fetch("/api/progress",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({profileId:id,...patch})}); if(!res.ok){setStatus("Не удалось сохранить изменения.");return;} await refresh(id); setStatus("Сохранено."); }
  async function loadRanking(){ if(!scenarioId)return; const res=await fetch(`/api/leaderboard?scenarioId=${encodeURIComponent(scenarioId)}&scenarioVersion=${scenarioVersion}&difficulty=${encodeURIComponent(difficulty)}&mode=independent`); const result=await res.json(); setRows(result.rows??[]); }
  if(!data)return <p className="py-12 text-sm text-[var(--muted)]">Загружаем профиль…</p>;
  return <div className="space-y-8 pb-10">
    <header className="border-b border-[var(--card-border)] pb-6"><p className="text-xs font-medium uppercase tracking-[.1em] text-[var(--accent)]">Личный кабинет</p><h1 className="mt-2 text-4xl font-semibold">Мой прогресс</h1><p className="mt-3 max-w-2xl text-[var(--muted)]">Навыки, достижения и сравнение только между одинаковыми сценариями, сложностью и режимом.</p></header>
    <section className="grid gap-3 sm:grid-cols-3"><Stat label="Завершено раундов" value={data.totalAttempts}/><Stat label="Баллы исходов" value={data.totalPoints}/><Stat label="Навыков с наблюдениями" value={data.skills.length}/></section>
    <section className="rounded-2xl border border-[var(--accent)] bg-[var(--accent-soft)] p-5"><p className="text-xs font-medium uppercase tracking-[.1em] text-[var(--muted)]">Следующая практика</p><h2 className="mt-1 text-xl font-semibold">{data.recommendation.skill}</h2><p className="mt-2 text-sm">{data.recommendation.explanation}</p><a href={`/`} className="mt-3 inline-flex min-h-11 items-center rounded-lg bg-[var(--accent)] px-4 text-sm font-medium text-white">Выбрать сценарий ↗</a></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><h2 className="text-xl font-semibold">Навыки</h2>{data.skills.length? <div className="mt-4 space-y-4">{data.skills.map(skill=><div key={`${skill.mode}:${skill.name}`}><div className="flex justify-between gap-2 text-sm"><span>{skill.name}<small className="ml-2 text-[var(--muted)]">{skill.mode==="guided"?"тренировка":"самостоятельно"}</small></span><span>{skill.score}/100 · {skill.trend>0?`+${skill.trend}`:skill.trend===0?"без динамики":skill.trend} п.</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[var(--field)]"><div className="h-full rounded-full bg-[var(--accent)]" style={{width:`${skill.score}%`}}/></div><p className="mt-1 text-xs text-[var(--muted)]">Наблюдения в {skill.attempts} раундах</p></div>)}</div>:<p className="mt-3 text-sm text-[var(--muted)]">Завершите раунд, чтобы увидеть навыки по наблюдаемым действиям.</p>}</div>
      <div className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><h2 className="text-xl font-semibold">Достижения</h2><div className="mt-4 grid gap-2">{data.achievements.map(a=><div key={a.id} className={`rounded-xl border p-3 ${a.earned?"border-[var(--accent)] bg-[var(--accent-soft)]":"border-[var(--card-border)] opacity-65"}`}><div className="flex justify-between gap-3"><strong>{a.title}</strong><span aria-label={a.earned?"Получено":"Ещё не получено"}>{a.earned?"✓":"·"}</span></div><p className="text-sm text-[var(--muted)]">{a.description}</p></div>)}</div></div></section>
    <section className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><h2 className="text-xl font-semibold">Калибровка самооценки</h2><p className="mt-2 text-sm text-[var(--muted)]">Прочитайте примеры и выберите уровень действия. Это объясняет рубрику; баллы самих раундов по-прежнему считаются по наблюдаемым репликам.</p><div className="mt-4 grid gap-3 lg:grid-cols-3">{anchors.map(item=><fieldset key={item.id} className="rounded-xl border border-[var(--card-border)] p-4"><legend className="px-1 font-medium">{item.title}</legend><blockquote className="my-2 text-sm">{item.text}</blockquote><select aria-label={item.title} value={calibration[item.id]??""} onChange={e=>setCalibration({...calibration,[item.id]:Number(e.target.value)})} className="min-h-11 w-full rounded-lg border px-3"><option value="">Выберите ориентир</option>{[item.low,item.middle,item.high].map((label,index)=><option key={label} value={index+1}>{index+1}. {label}</option>)}</select></fieldset>)}</div><button type="button" onClick={()=>void save({calibration})} disabled={Object.keys(calibration).length<3} className="mt-4 min-h-11 rounded-lg bg-[var(--accent)] px-4 text-sm font-medium text-white disabled:opacity-40">Сохранить калибровку</button><span className="ml-3 text-sm text-[var(--muted)]">{data.calibrationReady?"Ориентиры просмотрены":"Выберите все три примера"}</span></section>
    <section className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><h2 className="text-xl font-semibold">Псевдоним и публичный рейтинг</h2><p className="mt-2 text-sm text-[var(--muted)]">Публикация выключена по умолчанию. В лидерборд попадут только псевдоним, лучший балл и число попыток. Переписки и цитаты из отчётов не публикуются.</p><div className="mt-4 flex flex-wrap gap-3"><label className="min-w-56 flex-1 text-sm">Псевдоним<input value={alias} maxLength={24} onChange={e=>setAlias(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border px-3"/></label><label className="flex items-center gap-2 self-end pb-3 text-sm"><input type="checkbox" checked={publicRanking} onChange={e=>setPublicRanking(e.target.checked)}/>Публиковать мой рейтинг</label><button type="button" onClick={()=>void save({alias,publicRanking})} className="min-h-11 self-end rounded-lg border border-[var(--card-border)] px-4 text-sm">Сохранить профиль</button></div><p aria-live="polite" className="mt-2 text-sm text-[var(--muted)]">{status} Локальный профиль не является аккаунтом и не синхронизируется между устройствами.</p></section>
    <section className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-semibold">Лидерборд сценария</h2><p className="mt-1 text-sm text-[var(--muted)]">Совпадают версия сценария, сложность и самостоятельный режим.</p></div><button onClick={()=>void loadRanking()} className="min-h-11 rounded-lg bg-[var(--accent)] px-4 text-sm text-white">Показать рейтинг</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><select value={scenarioId} onChange={e=>{const s=scenarios.find(item=>item.id===e.target.value);setScenarioId(e.target.value);setScenarioVersion(s?.version??1);}} className="min-h-11 rounded-lg border px-3" aria-label="Сценарий">{scenarios.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><select value={difficulty} onChange={e=>setDifficulty(e.target.value)} className="min-h-11 rounded-lg border px-3" aria-label="Сложность"><option>Базовая</option><option>Средняя</option><option>Высокая</option></select></div>{rows.length?<ol className="mt-4 divide-y divide-[var(--card-border)]">{rows.map((row,i)=><li key={`${row.alias}-${i}`} className="flex justify-between py-3"><span>{i+1}. {row.alias}<small className="ml-2 text-[var(--muted)]">{row.attempts} попыток</small></span><strong>{row.score} · {row.outcome}</strong></li>)}</ol>:<p className="mt-4 text-sm text-[var(--muted)]">Пока нет опубликованных результатов для этих условий. В рейтинг входят только самостоятельные завершённые попытки.</p>}</section>
    <section className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><h2 className="text-xl font-semibold">История попыток</h2>{data.attempts.length?<ul className="mt-3 divide-y divide-[var(--card-border)]">{data.attempts.slice().reverse().map(a=><li key={a.id} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><span>{a.scenarioTitle} · {a.difficulty} · {a.mode==="guided"?"с подсказками":"самостоятельно"}</span><span>{a.outcome?.label ?? "Без результата"} · {a.outcome?.score ?? 0} баллов{a.comparison?` · ${a.comparison.scoreDelta>0?"+":""}${a.comparison.scoreDelta} к прошлой попытке`:""}</span></li>)}</ul>:<p className="mt-3 text-sm text-[var(--muted)]">Здесь появятся ваши завершённые раунды.</p>}</section>
  </div>;
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-[var(--card-border)] bg-[var(--card)] p-4"><p className="text-sm text-[var(--muted)]">{label}</p><p className="mt-1 text-3xl font-semibold">{value}</p></div>}
