"use client";
import { useCallback, useEffect, useState } from "react";
import { Icon } from "@/components/Icon";
import Link from "next/link";

type Member = { id: string; name: string; role: string; finished: boolean };
type Line = { id: string; authorId: string; author: string; role: string; content: string; bot?: boolean };
type Room = { id: string; code: string; template: string; status: string; brief: string; role: string; members: Member[]; lines: Line[]; report: null | { outcome: string; shared: { quote: string; theory: string; insight: string }[]; participants: { name: string; role: string; notes: string[]; exercise: string }[]; alignment: string | null } };
type Session = { id: string; token: string; invite?: string };
type Search = { id: string; token: string };
const storageKey = "arena-group-room";
const templates = [{ id: "client-seller", title: "Клиент и продавец", format: "Два человека, противоположные стороны", detail: "Согласуйте условия пилота или обоснованно откажитесь от сделки." }, { id: "project-team", title: "Команда защищает план проекта", format: "Два человека против руководителя и заказчика-ботов", detail: "Уточните приоритеты и предложите этапный план с ответственными и датой проверки." }, { id: "solo-board", title: "План проекта с двумя ботами", format: "Один человек против руководителя и заказчика-ботов", detail: "Потренируйтесь в индивидуальном раунде с несколькими собеседниками." }];

export default function GroupPage() {
  const [name, setName] = useState(""); const [session, setSession] = useState<Session | null>(null); const [room, setRoom] = useState<Room | null>(null);
  const [invite, setInvite] = useState(""); const [text, setText] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [origin, setOrigin] = useState("");
  const [search, setSearch] = useState<Search | null>(null);
  const auth: Record<string, string> = session ? { Authorization: `Bearer ${session.token}` } : {};
  useEffect(() => { setOrigin(window.location.origin); const query = new URLSearchParams(location.search); const incoming = query.get("invite"); if (incoming) setInvite(incoming); const saved = localStorage.getItem(storageKey); if (saved && !incoming) { try { setSession(JSON.parse(saved) as Session); } catch { localStorage.removeItem(storageKey); } } const savedSearch = localStorage.getItem(`${storageKey}-search`); if (savedSearch && !incoming) { try { setSearch(JSON.parse(savedSearch) as Search); } catch { localStorage.removeItem(`${storageKey}-search`); } } }, []);
  const refresh = useCallback(async (current: Session) => { const res = await fetch(`/api/group-rooms/${current.id}`, { headers: { Authorization: `Bearer ${current.token}` }, cache: "no-store" }); if (res.ok) setRoom(await res.json() as Room); else { localStorage.removeItem(storageKey); setSession(null); setRoom(null); setNotice("Доступ к сохранённой комнате истёк или отозван."); } }, []);
  useEffect(() => { if (!session) return; let alive = true; const tick = async () => { if (!alive) return; await refresh(session); }; void tick(); const timer = window.setInterval(tick, 2200); return () => { alive = false; window.clearInterval(timer); }; }, [session, refresh]);
  useEffect(() => { if (!search) return; let alive = true; const poll = async () => { const res = await fetch(`/api/group-matchmaking/${search.id}`, { headers: { Authorization: `Bearer ${search.token}` }, cache: "no-store" }); if (!alive) return; if (!res.ok) { localStorage.removeItem(`${storageKey}-search`); setSearch(null); setNotice("Поиск завершён по времени. Запустите его ещё раз."); return; } const data = await res.json(); if (!data.waiting) { const next = { id: data.roomId as string, token: data.token as string }; localStorage.removeItem(`${storageKey}-search`); localStorage.setItem(storageKey, JSON.stringify(next)); window.history.replaceState({}, "", `/group?room=${next.id}`); setSearch(null); setSession(next); setNotice("Соперник найден. Комната открыта."); } }; void poll(); const timer = window.setInterval(() => void poll(), 1800); return () => { alive = false; window.clearInterval(timer); }; }, [search]);
  async function enter(action: "create" | "join", template?: string) { setBusy(true); setNotice(""); try { const res = await fetch("/api/group-rooms", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, template, name, invite }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); const next = { id: data.room.id, token: data.token, ...(data.invite ? { invite: data.invite } : {}) }; localStorage.setItem(storageKey, JSON.stringify(next)); window.history.replaceState({}, "", `/group?room=${next.id}`); setSession(next); setRoom(data.room as Room); } catch (error) { setNotice(error instanceof Error ? error.message : "Не удалось подключиться"); } finally { setBusy(false); } }
  async function searchOpponent() { setBusy(true); try { const res = await fetch("/api/group-rooms", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "matchmake", name }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); const next = { id: data.ticketId, token: data.ticketToken }; localStorage.setItem(`${storageKey}-search`, JSON.stringify(next)); setSearch(next); } catch (error) { setNotice(error instanceof Error ? error.message : "Не удалось начать поиск"); } finally { setBusy(false); } }
  async function cancelSearch() { if (!search) return; const res = await fetch(`/api/group-matchmaking/${search.id}`, { method: "DELETE", headers: { Authorization: `Bearer ${search.token}` } }); if (res.status === 409) { const match = await fetch(`/api/group-matchmaking/${search.id}`, { headers: { Authorization: `Bearer ${search.token}` }, cache: "no-store" }); if (match.ok) { const data = await match.json(); if (!data.waiting) { const next = { id: data.roomId as string, token: data.token as string }; localStorage.removeItem(`${storageKey}-search`); localStorage.setItem(storageKey, JSON.stringify(next)); setSearch(null); setSession(next); setNotice("Соперник найден одновременно с остановкой поиска."); return; } } } localStorage.removeItem(`${storageKey}-search`); setSearch(null); setNotice("Поиск соперника остановлен."); }
  async function send() { if (!session || !text.trim()) return; setBusy(true); try { const res = await fetch(`/api/group-rooms/${session.id}/messages`, { method: "POST", headers: { ...auth, "Content-Type": "application/json" }, body: JSON.stringify({ text }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setRoom(data as Room); setText(""); } catch (error) { setNotice(error instanceof Error ? error.message : "Не удалось отправить реплику"); } finally { setBusy(false); } }
  async function finish() { if (!session) return; setBusy(true); try { const res = await fetch(`/api/group-rooms/${session.id}/finish`, { method: "POST", headers: auth }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setRoom(data as Room); } catch (error) { setNotice(error instanceof Error ? error.message : "Не удалось завершить раунд"); } finally { setBusy(false); } }
  const currentInvite = session?.invite ? `${origin}/group?invite=${session.invite}` : "";
  const lastHuman = room?.lines.filter((line) => !line.bot).at(-1);
  const canSpeak = room?.status === "active" && (room.template === "project-team" || !lastHuman || lastHuman.role !== room.role);

  return <div className="group-page mx-auto max-w-5xl pb-12">
    <header className="dossier-intro">
      <div><p className="section-kicker">Совместная практика</p><h1>У каждой стороны —<br />своя версия истории.</h1></div>
      <div><p className="text-sm leading-6 text-[var(--muted)]">Выберите собеседника и формат. В комнате каждый участник получит свой бриф: общую картину предстоит собрать в разговоре.</p>{session && <Link href="/group" onClick={(e) => { e.preventDefault(); localStorage.removeItem(storageKey); setRoom(null); setSession(null); window.history.replaceState({}, "", "/group"); }} className="mt-4 inline-flex min-h-11 items-center rounded-xl border border-[var(--card-border)] px-4 py-2 text-sm">Выйти из комнаты</Link>}</div>
    </header>
    {!session && <div className="lobby-identity"><label htmlFor="lobby-name" className="text-sm font-medium">Как вас представить собеседнику?</label><input id="lobby-name" value={name} onChange={(e) => setName(e.target.value)} placeholder="Ваше имя" maxLength={40} className="min-h-11 min-w-0 rounded-xl border px-3 py-2.5"/><p className="text-xs text-[var(--muted)]">Это имя будет видно участникам комнаты.</p></div>}
    {!session && <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
      <section className="space-y-3"><h2 className="text-lg font-medium">С кем будете договариваться?</h2>{templates.map((item) => <article key={item.id} className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold">{item.title}</h3><p className="mt-1 text-xs text-[var(--accent)]">{item.format}</p><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{item.detail}</p></div><span aria-hidden="true" className="text-xl text-[var(--accent)]"><Icon name="arrow-up-right" /></span></div><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy || !name.trim() || Boolean(search)} onClick={() => void enter("create", item.id)} className="rounded-xl bg-[var(--accent)] px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{item.id === "solo-board" ? "Начать" : "Создать"}</button>{item.id === "client-seller" && <button disabled={busy || !name.trim() || Boolean(search)} onClick={() => void searchOpponent()} className="rounded-xl border border-[var(--card-border)] px-4 py-2 text-sm disabled:opacity-50">Найти случайного соперника</button>}</div></article>)}{search && <div className="flex items-center justify-between gap-3 rounded-2xl border border-[var(--accent)]/40 bg-[var(--card)] p-4" role="status"><p className="text-sm">Ищем соперника для переговоров «Клиент и продавец»…</p><button onClick={() => void cancelSearch()} className="rounded-lg border border-[var(--card-border)] px-3 py-2 text-sm">Остановить</button></div>}</section>
      <section className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><h2 className="text-xl font-semibold">Уже есть приглашение?</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Откройте ссылку от ведущего или вставьте ключ приглашения.</p><label className="mt-4 block text-sm">Ключ приглашения<input value={invite} onChange={(e) => setInvite(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-3 font-mono" placeholder="Ключ из ссылки"/></label><button disabled={busy || !name.trim() || !invite.trim()} onClick={() => void enter("join")} className="mt-4 min-h-11 w-full rounded-xl border border-[var(--card-border)] px-4 text-sm font-medium disabled:opacity-50">Присоединиться</button></section>
    </div>}
    {room && <section className="grid min-w-0 gap-5 lg:grid-cols-[.8fr_1.2fr]"><aside className="min-w-0 space-y-4"><div className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-wider text-[var(--muted)]">{room.template === "solo-board" ? "Индивидуальный раунд" : `Комната ${room.code}`}</span><span className="rounded-full bg-white/5 px-3 py-1 text-xs">{room.status === "waiting" ? "Ожидание" : room.status === "completed" ? "Завершена" : "Идёт раунд"}</span></div><h2 className="mt-4 text-xl font-semibold">{templates.find((t) => t.id === room.template)?.title}</h2><p className="mt-2 text-sm text-[var(--accent)]">Ваша роль: {room.role}</p><div className="mt-4 rounded-xl bg-white/[.04] p-4"><p className="text-xs uppercase tracking-wider text-[var(--muted)]">Ваш личный бриф</p><p className="mt-2 text-sm leading-6">{room.brief}</p></div>{currentInvite && room.status === "waiting" && <div className="mt-4 rounded-xl border border-[var(--card-border)] p-3"><p className="text-xs text-[var(--muted)]">Ссылка-приглашение (одно место)</p><div className="mt-2 flex gap-2"><input readOnly value={currentInvite} className="min-w-0 flex-1 rounded-lg border px-2 py-2 text-xs"/><button onClick={() => void navigator.clipboard.writeText(currentInvite).then(() => setNotice("Ссылка скопирована."))} className="rounded-lg border border-[var(--card-border)] px-3 text-xs">Копировать</button></div></div>}</div><div className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><h3 className="font-medium">Участники</h3><ul className="mt-3 space-y-2">{room.members.map((m) => <li key={m.id} className="flex items-center justify-between text-sm"><span>{m.name} <span className="text-[var(--muted)]">· {m.role}</span></span><span className="text-xs text-[var(--accent)]">{m.finished ? "Готов" : "На связи"}</span></li>)}{room.status === "waiting" && <li className="text-sm text-[var(--muted)]">Ждём второго участника…</li>}</ul>{room.status === "active" && <button disabled={busy || room.members.find((m) => m.role === room.role)?.finished} onClick={() => void finish()} className="mt-4 min-h-11 rounded-xl border border-[var(--card-border)] px-4 text-sm">Завершить свой раунд</button>}</div></aside>
      <div className="min-w-0 space-y-4"><div className="min-h-[360px] space-y-3 rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-4 sm:p-6" aria-live="polite">{room.lines.length === 0 ? <div className="grid min-h-[320px] place-items-center text-center"><div><span className="text-3xl">◎</span><p className="mt-3 text-sm text-[var(--muted)]">{room.status === "waiting" ? "Диалог откроется, когда участник присоединится." : "Начните диалог с вопроса о приоритетах собеседника."}</p></div></div> : room.lines.map((line) => <article key={line.id} className={`max-w-[92%] rounded-2xl p-4 ${line.authorId && room.members.some((m) => m.id === line.authorId && m.role === room.role) ? "ml-auto bg-[var(--accent)]/15" : "bg-white/[.05]"}`}><p className="text-[11px] text-[var(--muted)]">{line.author} · {line.role}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6">{line.content}</p></article>)}</div>{room.status === "active" && <form onSubmit={(e) => { e.preventDefault(); void send(); }} className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-3"><label htmlFor="group-message" className="sr-only">Ваша реплика</label><textarea id="group-message" value={text} onChange={(e) => setText(e.target.value)} disabled={!canSpeak || busy} maxLength={2000} rows={3} placeholder={canSpeak ? "Напишите реплику…" : "Очередь другого участника — обновления появятся автоматически."} className="w-full resize-y rounded-xl border p-3 disabled:opacity-60"/><div className="mt-2 flex justify-end"><button disabled={!canSpeak || busy || !text.trim()} className="min-h-11 rounded-xl bg-[var(--accent)] px-5 text-sm font-medium text-white disabled:opacity-50">Отправить реплику</button></div></form>}{room.report && <div className="rounded-2xl border border-[var(--accent)]/40 bg-[var(--card)] p-5"><p className="text-xs uppercase tracking-widest text-[var(--accent)]">Разбор раунда</p><h3 className="mt-2 text-xl font-semibold">{room.report.outcome}</h3>{room.report.shared.map((point, i) => <div key={i} className="mt-4 border-t border-[var(--card-border)] pt-3"><p className="text-sm font-medium">«{point.quote}»</p><p className="mt-1 text-xs text-[var(--accent)]">{point.theory}</p><p className="mt-1 text-sm text-[var(--muted)]">{point.insight}</p></div>)}{room.report.alignment && <p className="mt-4 rounded-xl bg-white/[.04] p-3 text-sm">Согласованность команды: {room.report.alignment}</p>}{room.report.participants.filter((p) => p.role === room.role).map((person) => <div key={person.name} className="mt-4 rounded-xl bg-white/[.04] p-4"><h4 className="text-sm font-semibold">Ваш персональный разбор</h4><p className="mt-2 text-sm text-[var(--muted)]">{person.notes.length ? `Ваши реплики: ${person.notes.map((n) => `«${n}»`).join(" · ")}` : "В раунде пока нет ваших реплик."}</p><p className="mt-3 text-sm">Упражнение: {person.exercise}</p></div>)}</div>}</div></section>}
    {notice && <p role="status" className="rounded-xl border border-[var(--card-border)] px-4 py-3 text-sm text-[var(--muted)]">{notice}</p>}
    <p className="text-xs leading-5 text-[var(--muted)]">Локальная демонстрация: ссылка работает только при доступности этого экземпляра приложения. Для боевого многопользовательского запуска нужны общая БД, аккаунты и централизованная синхронизация.</p>
  </div>;
}
